---
name: "Invalidate cloudfront"
description: "Build and push docker images to a registry"

inputs:
  # Login
  aws-access-key-id:
    description: "AWS access key ID"
    required: true
  aws-secret-access-key:
    description: "AWS secret access key"
    required: true
  aws-region:
    description: "AWS Region"
    required: true
  aws_role_to_assume:
    description: "AWS role arn to assume"
    required: false
  # Build
  source-dir:
    description: "The local directory (or file) you wish to sync/upload to S3. For example, dist. Defaults to your entire repository."
    required: false
    default: "."
  s3-bucket:
    description: "The name of the bucket you're syncing to."
    required: true
  dest-dir:
    description: "The directory inside of the S3 bucket you wish to sync/upload to. Defaults to the root of the bucket."
    required: false

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.aws_role_to_assume }}
        role-skip-session-tagging: true
        role-duration-seconds: 3600

    - name: Invalidate CloudFront cache
      shell: bash
      run: |
        aws s3 sync ${{ inputs.source-dir }} s3://${{ inputs.s3-bucket }}/${{ inputs.dest-dir }}